name: ChickenFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: Plugin for the ChickenFreedom server.
depend: [Aero, WorldEdit, Essentials]
softdepend: [BukkitTelnet, Essentials]
authors: [Madgeek1450, Prozza, Mayoralty, savykilo, awesomegamer175]

